# Generated by Django 6.0.2 on 2026-03-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-data_coleta', '-score']},
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='preco_atual',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='produto',
            name='loja',
            field=models.CharField(choices=[('ML', 'Mercado Livre'), ('KB', 'KaBuM'), ('TB', 'Terabyte')], max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=500),
        ),
    ]
